### ISSUE TITLE
SQLiteDataStore doesn't close file after being disposed

### ISSUE THREAD

**Issue by mshindal** [ctacke/orm#2]
I get an exception when I try to read the SQLite file created by an `SQLiteDataStore` even after I called `Dispose()`.

```
var path = @"C:\Users\mshindala\Desktop\test.sqlite";
var store = new SQLiteDataStore(path);
store.CreateStore();
store.Dispose();
var fs = new FileStream(path, FileMode.Open); // Throws exception: 'The process cannot access the file 'C:\Users\mshindala\Desktop\test.sqlite' because it is being used by another process.'
```

**Comment by ctacke** [comment]
I'll take a look.  I use the SQLite store a lot, but I don't think I've ever tried what you're doing.  Generally I open a data service at app startup, and it stays up until the app ends.

**Comment by ctacke** [comment]
Found, fixed and published in build 17237.  Thanks for the report - that's how it gets better.
